version: 0.2
env:
  variables:
    ECR_REPO_NAME: api-repository
phases:
  pre_build:
    commands:
      - echo "hello"

      #ECR login
      - ECR_MAIN_URI="423623841339.dkr.ecr.ap-northeast-1.amazonaws.com"
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${ECR_MAIN_URI}

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
  build:
    commands:
      - docker build -t api-server:latest .
  post_build:
    commands:
      - docker tag api-server:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}

      #step3  Generate image definitions file for ECS
      #- printf '[{"name":"code-nginx-contaier-name","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
      - printf '{"ImageURI":"%s"}' ${ECR_IMAGE_URI} > imageDetail.json

artifacts:
  files:
    #    - imagedefinitions.json
    - appspec.yml
    - taskdef.json
    - imageDetail.json
